# https://rubenvanassche.com/testing-php-packages-with-github-actions/
name: Tests (develop)

on:
  push:
    branches-ignore:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: [7.3, 7.4]

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, fileinfo, pdo_sqlite
          ini-values: "post_max_size=256M"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist
        env:
          APP_ENV: testing
        
      - name: Run tests
        run: ./vendor/bin/phpunit
        env:
          APP_ENV: testing