# https://rubenvanassche.com/testing-php-packages-with-github-actions/
name: Tests (master)

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    
    strategy:
      matrix:
        operating-system: [ubuntu-latest] # , windows-latest, macOS-latest
        php-versions: [7.3, 7.4, 8.0]
        laravel: [6.*, 7.*, 8.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 6.*
            testbench: 4.*
          - laravel: 7.*
            testbench: 5.*
          - laravel: 8.*
            testbench: 6.*

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }} Laravel v${{ matrix.laravel }} Testbench v${{ matrix.testbench }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, fileinfo, pdo_sqlite
          ini-values: "post_max_size=256M"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist
        env:
          APP_ENV: testing
        
      - name: Run tests
        run: ./vendor/bin/phpunit
        env:
          APP_ENV: testing